# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Choice', models.CharField(max_length=10000)),
                ('Score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('QId', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=1000)),
                ('Email', models.EmailField(max_length=1000)),
                ('Zip', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='answerto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Userinfo.Question'),
        ),
    ]
